name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
    - name: Cross compile
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        rustup target add aarch64-unknown-linux-gnu
        cargo build -p yamanote-node-rp4 --release --target aarch64-unknown-linux-gnu
        file target/aarch64-unknown-linux-gnu/release/yamanote-node-rp4
